In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use("ggplot")

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/vincentgupo/dengue-cases-in-the-philippines/ph_dengue_cases2016-2020.csv

# DATA EXTRACTION #

In [2]:
df = pd.read_csv("/kaggle/input/datasets/vincentgupo/dengue-cases-in-the-philippines/ph_dengue_cases2016-2020.csv")

df.head(3)

      Month  Year    Region  Dengue_Cases  Dengue_Deaths
0   January  2016  Region I           705              1
1  February  2016  Region I           374              0
2     March  2016  Region I           276              0

### Renaming the columns ###

In [3]:
df = df.rename(columns={
    "Month":"month",
    "Year":"year",
    "Region":"region",
    "Dengue_Cases":"dengue_cases",
    "Dengue_Death":"dengue_deaths"
})

df.head(3)

      month  year    region  dengue_cases  Dengue_Deaths
0   January  2016  Region I           705              1
1  February  2016  Region I           374              0
2     March  2016  Region I           276              0

### Describing the values ###

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   month          1020 non-null   object
 1   year           1020 non-null   int64
 2   region         1020 non-null   object
 3   dengue_cases   1020 non-null   int64
 4   Dengue_Deaths  1020 non-null   int64
dtypes: int64(3), object(2)
memory usage: 40.0+ KB

In [5]:
df.describe()

              year  dengue_cases  Dengue_Deaths
count  1020.000000   1020.000000    1020.000000
mean   2018.000000   1124.926471      16.513725
std       1.414907   1662.608878      96.358215
min    2016.000000     10.000000       0.000000
25%    2017.000000    247.750000       1.000000
50%    2018.000000    582.500000       3.000000
75%    2019.000000   1284.250000       7.000000
max    2020.000000  21658.000000    1651.000000

### Transforming the dataset ###

#### Remapping the month into numberss ####

In [6]:
df["month_num"] = df["month"].map({
    "January":1,
    "February":2,
    "March":3,
    "April":4,
    "May":5,
    "June":6,
    "July":7,
    "August":8,
    "September":9,
    "October":10,
    "November":11,
    "December":12
})

df["month_num"].value_counts()

month_num
1     85
2     85
3     85
4     85
5     85
6     85
7     85
8     85
9     85
10    85
11    85
12    85
Name: count, dtype: int64

#### Creating the datetime column ####

In [7]:
df["month_year"] = pd.to_datetime(
    dict(
        year=df["year"],
        month=df["month_num"],
        day=1
    )
)

df.head(5)

      month  year    region  dengue_cases  Dengue_Deaths  month_num month_year
0   January  2016  Region I           705              1          1 2016-01-01
1  February  2016  Region I           374              0          2 2016-02-01
2     March  2016  Region I           276              0          3 2016-03-01
3     April  2016  Region I           240              2          4 2016-04-01
4       May  2016  Region I           243              1          5 2016-05-01